Catching up with six weeks worth of minor adjustments to the original DiP3.

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -85,18 +85,10 @@ done
 # build sitemap
 ls build/*.html | sed -e "s|build/|http://gpiancastelli.altervista.org/dip3-it/|g" -e "s|/index.html|/|g" > build/sitemap.txt || die "Failed to build sitemap"
 
-echo "adding evil tracking code"
-# add Google Analytics script
-for f in build/*.html; do
-  cat "$f" j/ga.js > build/tmp && \
-      mv build/tmp "$f" || die "Could not add tracking code to $f"
-done
-
 # minimize JS and CSS
 echo "minimizing JS"
-revision=`hg log|grep changeset|cut -d":" -f3|head -1`
-java -jar util/yuicompressor-2.4.2.jar build/j/prettify.js > build/j/prettify.min.js && \
-    java -jar util/yuicompressor-2.4.2.jar build/j/dip3.js > build/j/dip3.min.js || die "Failed to minimize JS"
+java -jar util/compiler.jar build/j/prettify.js > build/j/prettify.min.js && \
+    java -jar util/compiler.jar build/j/dip3.js > build/j/dip3.min.js || die "Failed to minimize JS"
 
 # combine jQuery and our script
 echo "combining JS"
@@ -114,19 +106,19 @@ java -jar util/yuicompressor-2.4.2.jar build/dip3.css > build/$revision.css && \
     sed -i -e "s|;}|}|g" build/p-$revision.css || die "Failed to minimize CSS"
 
 # put CSS inline and remove unused CSS properties on a page-by-page basis
-echo "inlining CSS"
+# minimize URLs by stripping "http:" prefix
+# add asynchronous Google Analytics script in head (after inline styles)
+echo "inlining CSS, minimizing URLs, adding evil tracking code"
+ga=`cat j/ga.js`
 for f in build/*.html; do
   css=`python2.6 util/lesscss.py "$f" "build/$revision.css"` || die "Failed to remove unused CSS"
   mobilecss=`python2.6 util/lesscss.py "$f" "build/m-$revision.css"` || die "Failed to remove unused CSS"
   printcss=`python2.6 util/lesscss.py "$f" "build/p-$revision.css"` || die "Failed to remove unused CSS"
   sed -i -e "s|<link rel=stylesheet href=dip3.css>|<style>${css}</style>|g" -e "s|<link rel=stylesheet media='only screen and (max-device-width: 480px)' href=mobile.css>|<style>@media screen and (max-device-width:480px){${mobilecss}}</style>|g" -e "s|<link rel=stylesheet media=print href=print.css>|<style>@media print{${printcss}}</style>|g" -e "s|</style><style>||g" "$f" || die "Failed to inline CSS"
+  # files are not available from URL root
+  sed -i -e "s|=http:|=|g" -e "s|href=index.html|href=/dip3-it|g" "$f" || die "Failed to minimize URLs"
+  sed -i -e "s|</style>|</style>${ga}|g" "$f" || die "Failed to add evil tracking code"
 done
-
-# minimize URLs
-echo "minimizing URLs"
-sed -i -e "s|=http:|=|g" build/*.html && \
-    # files are not available from URL root
-    sed -i -e "s|href=index.html|href=/dip3-it|g" build/*.html || die "Failed to minimize URLs"
 
 # set file permissions (hg resets these, don't know why)
 chmod 755 build/esempi build/j build/i build/d && \
