Kiss my CSS styles goodbye.

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -102,11 +102,9 @@ cat build/j/jquery.min.js build/j/prettify.min.js build/j/dip3.min.js > build/j/
 
 echo "minimizing CSS"
 java -jar util/yuicompressor-2.4.2.jar build/dip3.css > build/$revision.css && \
-    java -jar util/yuicompressor-2.4.2.jar build/dip3-it.css > build/$revision-it.css && \
     java -jar util/yuicompressor-2.4.2.jar build/mobile.css > build/m-$revision.css && \
     java -jar util/yuicompressor-2.4.2.jar build/print.css > build/p-$revision.css && \
     sed -i -e "s|;}|}|g" build/$revision.css && \
-    sed -i -e "s|;}|}|g" build/$revision-it.css && \
     sed -i -e "s|;}|}|g" build/m-$revision.css && \
     sed -i -e "s|;}|}|g" build/p-$revision.css || die "Failed to minimize CSS"
 
@@ -114,10 +112,9 @@ java -jar util/yuicompressor-2.4.2.jar build/dip3.css > build/$revision.css && \
 echo "inlining CSS"
 for f in build/*.html; do
   css=`python2.6 util/lesscss.py "$f" "build/$revision.css"` || die "Failed to remove unused CSS"
-  cssit=`python2.6 util/lesscss.py "$f" "build/$revision-it.css"` || die "Failed to remove unused CSS"
   mobilecss=`python2.6 util/lesscss.py "$f" "build/m-$revision.css"` || die "Failed to remove unused CSS"
   printcss=`python2.6 util/lesscss.py "$f" "build/p-$revision.css"` || die "Failed to remove unused CSS"
-  sed -i -e "s|<link rel=stylesheet href=dip3.css>|<style>${css}</style>|g" -e "s|<link rel=stylesheet href=dip3-it.css>|<style>${cssit}</style>|g" -e "s|<link rel=stylesheet media='only screen and (max-device-width: 480px)' href=mobile.css>|<style>@media screen and (max-device-width:480px){${mobilecss}}</style>|g" -e "s|<link rel=stylesheet media=print href=print.css>|<style>@media print{${printcss}}</style>|g" -e "s|</style><style>||g" "$f" || die "Failed to inline CSS"
+  sed -i -e "s|<link rel=stylesheet href=dip3.css>|<style>${css}</style>|g" -e "s|<link rel=stylesheet media='only screen and (max-device-width: 480px)' href=mobile.css>|<style>@media screen and (max-device-width:480px){${mobilecss}}</style>|g" -e "s|<link rel=stylesheet media=print href=print.css>|<style>@media print{${printcss}}</style>|g" -e "s|</style><style>||g" "$f" || die "Failed to inline CSS"
 done
 
 # minimize URLs
