Add validation to build process.

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -28,6 +28,11 @@ cp -R esempi build/
 # not copying .htaccess files because of my server limitations
 #cp .htaccess build/
 
+echo "validating HTML"
+for f in *.html; do
+  python3 util/validate.py "$f" > /dev/null || die "Failed to validate $f"
+done
+
 echo "building HTML distribution"
 htmlbasedir=diveintopython3-it-r"$revision"-"$today"
 htmldir=build/"$htmlbasedir"
